services:
  db:
    image: postgres:12
    volumes:
      - ../../.docker/dev/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD

  api:
    build:
      context: ../../
      dockerfile: ./deploy/rbtgen_dev/dev.api.Dockerfile
    volumes:
      - ../../:/var/src/
    environment:
      - POSTGRES_PASSWORD
    depends_on:
      - db

  web:
    build:
      context: ../../client
      dockerfile: ../deploy/rbtgen_dev/dev.web.Dockerfile
    volumes:
      - ../../client:/var/src/
    depends_on:
      - api

  proxy:
    build:
      context: .
      dockerfile: dev.proxy.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api
      - web