services:
  db:
    image: postgres:12
    volumes:
      - ../../.docker/prod/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=rbt_gen
      - POSTGRES_DB=rbt_gen_production

  api:
    build:
      context: ../../
      dockerfile: ./deploy/rbtgen_prod/prod.api.Dockerfile
    volumes:
      - ../../:/var/src/
    environment:
      - POSTGRES_PASSWORD
    depends_on:
      - db

  proxy:
    build:
      context: ../../
      dockerfile: ./deploy/rbtgen_prod/prod.proxy.Dockerfile
    volumes:
      - ../../client/dist/:/usr/local/apache2/htdocs/
    ports:
      - 4269:80
    depends_on:
      - api