openapi: 3.0.1

info:
  title: RBTgen API
  version: 1.0.0

servers:
  - url: /rest/v1/

paths:
  /public/account/login:
    $ref: "account/account.api.yml#/login"
  /public/account/signup:
    $ref: "account/account.api.yml#/signup"
