openapi: 3.0.1

info:
  title: RBTgen API
  version: 1.0.0

servers:
  - url: /rest/v1/

paths:
  /public/account/login:
    $ref: "account/account.api.yml#/login"
  /public/account/signup:
    $ref: "account/account.api.yml#/signup"

  /authenticated/user/self/documents/:
    $ref: "user/document/schema_document.api.yml#/getDocuments"
  /authenticated/user/self/document:
    $ref: "user/document/schema_document.api.yml#/addDocument"
  /authenticated/user/self/document/{document_id}:
    $ref: "user/document/schema_document.api.yml#/Document"
