openapi: 3.0.1

login_credentials:
  required:
    - user_name
    - password
  properties:
    user_name:
      type: string
    password:
      type: string

auth_token:
  required:
    - token
  properties:
    token:
      type: string
